<<<<<<< HEAD
=======


>>>>>>> 32a544af70d8c0f1c4a2ddbe4343d7e5b71a61c8
services:
  cv-to-json:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - NAME=World
    stdin_open: true
    tty : true
    volumes:
      - .:/app
    command: ["python", "cv_to_json.py"]
