services:
  routes:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - NAME=World
    stdin_open: true
    tty : true
    volumes:
      - .:/app
    command: ["python", "routes.py"]
